FROM amazoncorretto:17.0.10-alpine

ARG version
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG FIREBASE_DATA_CONFIG
ARG AWS_S3_BUCKET
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG OPENAI_API_KEY
ARG BOOK_RECOMMENDATION_API_URL
ARG PDF_READING_API_URL
ARG JAR_FILE=build/libs/bookwel-api-$version.jar

ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV FIREBASE_DATA_CONFIG=${FIREBASE_DATA_CONFIG}
ENV AWS_S3_BUCKET=${AWS_S3_BUCKET}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV BOOK_RECOMMENDATION_API_URL=${BOOK_RECOMMENDATION_API_URL}
ENV PDF_READING_API_URL=${PDF_READING_API_URL}
ENV JAVA_OPTS="-Xmx1g"

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 8080