name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-maven-${{ hashFiles('**/build.gradle', '**/api.yml') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - run: chmod +x gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - run: ./gradlew test --info